TaskTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.TASK_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
